// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.swingfrog.summer.protocol.protobuf.proto;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeat_Req_0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat_Req_0)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code HeartBeat_Req_0}
   */
  public static final class HeartBeat_Req_0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeat_Req_0)
      HeartBeat_Req_0OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeat_Req_0.newBuilder() to construct.
    private HeartBeat_Req_0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat_Req_0() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeat_Req_0();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat_Req_0(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HeartBeat_Req_0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HeartBeat_Req_0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 other = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat_Req_0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat_Req_0)
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HeartBeat_Req_0_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HeartBeat_Req_0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.Builder.class);
      }

      // Construct using com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HeartBeat_Req_0_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 getDefaultInstanceForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 build() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 buildPartial() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 result = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0) {
          return mergeFrom((com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 other) {
        if (other == com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeat_Req_0)
    }

    // @@protoc_insertion_point(class_scope:HeartBeat_Req_0)
    private static final com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0();
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeat_Req_0>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat_Req_0>() {
      @java.lang.Override
      public HeartBeat_Req_0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat_Req_0(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat_Req_0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat_Req_0> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HeartBeat_Req_0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HearBeat_Resp_0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HearBeat_Resp_0)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    long getTime();
  }
  /**
   * Protobuf type {@code HearBeat_Resp_0}
   */
  public static final class HearBeat_Resp_0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HearBeat_Resp_0)
      HearBeat_Resp_0OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HearBeat_Resp_0.newBuilder() to construct.
    private HearBeat_Resp_0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HearBeat_Resp_0() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HearBeat_Resp_0();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HearBeat_Resp_0(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HearBeat_Resp_0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HearBeat_Resp_0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 other = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0) obj;

      if (getTime()
          != other.getTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HearBeat_Resp_0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HearBeat_Resp_0)
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HearBeat_Resp_0_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HearBeat_Resp_0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.Builder.class);
      }

      // Construct using com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_HearBeat_Resp_0_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 getDefaultInstanceForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 build() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 buildPartial() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 result = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0(this);
        result.time_ = time_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0) {
          return mergeFrom((com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 other) {
        if (other == com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HearBeat_Resp_0)
    }

    // @@protoc_insertion_point(class_scope:HearBeat_Resp_0)
    private static final com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0();
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HearBeat_Resp_0>
        PARSER = new com.google.protobuf.AbstractParser<HearBeat_Resp_0>() {
      @java.lang.Override
      public HearBeat_Resp_0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HearBeat_Resp_0(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HearBeat_Resp_0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HearBeat_Resp_0> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.HearBeat_Resp_0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorCode_Push_1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorCode_Push_1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 reqId = 1;</code>
     * @return The reqId.
     */
    int getReqId();

    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code ErrorCode_Push_1}
   */
  public static final class ErrorCode_Push_1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorCode_Push_1)
      ErrorCode_Push_1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorCode_Push_1.newBuilder() to construct.
    private ErrorCode_Push_1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorCode_Push_1() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ErrorCode_Push_1();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorCode_Push_1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              reqId_ = input.readInt32();
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_ErrorCode_Push_1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_ErrorCode_Push_1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.Builder.class);
    }

    public static final int REQID_FIELD_NUMBER = 1;
    private int reqId_;
    /**
     * <code>int32 reqId = 1;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public int getReqId() {
      return reqId_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqId_ != 0) {
        output.writeInt32(1, reqId_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqId_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 other = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1) obj;

      if (getReqId()
          != other.getReqId()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ErrorCode_Push_1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorCode_Push_1)
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_ErrorCode_Push_1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_ErrorCode_Push_1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.class, com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.Builder.class);
      }

      // Construct using com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reqId_ = 0;

        code_ = 0;

        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.internal_static_ErrorCode_Push_1_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 getDefaultInstanceForType() {
        return com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 build() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 buildPartial() {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 result = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1(this);
        result.reqId_ = reqId_;
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1) {
          return mergeFrom((com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 other) {
        if (other == com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1.getDefaultInstance()) return this;
        if (other.getReqId() != 0) {
          setReqId(other.getReqId());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqId_ ;
      /**
       * <code>int32 reqId = 1;</code>
       * @return The reqId.
       */
      @java.lang.Override
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>int32 reqId = 1;</code>
       * @param value The reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqId(int value) {
        
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqId() {
        
        reqId_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 3;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ErrorCode_Push_1)
    }

    // @@protoc_insertion_point(class_scope:ErrorCode_Push_1)
    private static final com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1();
    }

    public static com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorCode_Push_1>
        PARSER = new com.google.protobuf.AbstractParser<ErrorCode_Push_1>() {
      @java.lang.Override
      public ErrorCode_Push_1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorCode_Push_1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorCode_Push_1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorCode_Push_1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.protocol.protobuf.proto.CommonProto.ErrorCode_Push_1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_Req_0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_Req_0_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HearBeat_Resp_0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HearBeat_Resp_0_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorCode_Push_1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorCode_Push_1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"\021\n\017HeartBeat_Req_0\"\037\n\017Hea" +
      "rBeat_Resp_0\022\014\n\004time\030\001 \001(\003\"<\n\020ErrorCode_" +
      "Push_1\022\r\n\005reqId\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022\013\n\003m" +
      "sg\030\003 \001(\tB;\n,com.swingfrog.summer.protoco" +
      "l.protobuf.protoB\013CommonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HeartBeat_Req_0_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_Req_0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_Req_0_descriptor,
        new java.lang.String[] { });
    internal_static_HearBeat_Resp_0_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HearBeat_Resp_0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HearBeat_Resp_0_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_ErrorCode_Push_1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErrorCode_Push_1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorCode_Push_1_descriptor,
        new java.lang.String[] { "ReqId", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
