// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.swingfrog.summer.test.protobuf.proto;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloWorld_Req_101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloWorld_Req_101)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code HelloWorld_Req_101}
   */
  public static final class HelloWorld_Req_101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HelloWorld_Req_101)
      HelloWorld_Req_101OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloWorld_Req_101.newBuilder() to construct.
    private HelloWorld_Req_101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloWorld_Req_101() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloWorld_Req_101();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloWorld_Req_101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Req_101_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Req_101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.class, com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 other = (com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HelloWorld_Req_101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HelloWorld_Req_101)
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Req_101_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Req_101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.class, com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.Builder.class);
      }

      // Construct using com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Req_101_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 getDefaultInstanceForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 build() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 buildPartial() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 result = new com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101) {
          return mergeFrom((com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 other) {
        if (other == com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HelloWorld_Req_101)
    }

    // @@protoc_insertion_point(class_scope:HelloWorld_Req_101)
    private static final com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101();
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloWorld_Req_101>
        PARSER = new com.google.protobuf.AbstractParser<HelloWorld_Req_101>() {
      @java.lang.Override
      public HelloWorld_Req_101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloWorld_Req_101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloWorld_Req_101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloWorld_Req_101> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Req_101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloWorld_Resp_101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloWorld_Resp_101)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg = 1;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code HelloWorld_Resp_101}
   */
  public static final class HelloWorld_Resp_101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HelloWorld_Resp_101)
      HelloWorld_Resp_101OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloWorld_Resp_101.newBuilder() to construct.
    private HelloWorld_Resp_101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloWorld_Resp_101() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloWorld_Resp_101();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloWorld_Resp_101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Resp_101_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Resp_101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.class, com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 1;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 1;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 other = (com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101) obj;

      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HelloWorld_Resp_101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HelloWorld_Resp_101)
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Resp_101_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Resp_101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.class, com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.Builder.class);
      }

      // Construct using com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_HelloWorld_Resp_101_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 getDefaultInstanceForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 build() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 buildPartial() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 result = new com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101(this);
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101) {
          return mergeFrom((com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 other) {
        if (other == com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101.getDefaultInstance()) return this;
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 1;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HelloWorld_Resp_101)
    }

    // @@protoc_insertion_point(class_scope:HelloWorld_Resp_101)
    private static final com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101();
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloWorld_Resp_101>
        PARSER = new com.google.protobuf.AbstractParser<HelloWorld_Resp_101>() {
      @java.lang.Override
      public HelloWorld_Resp_101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloWorld_Resp_101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloWorld_Resp_101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloWorld_Resp_101> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.test.protobuf.proto.TestProto.HelloWorld_Resp_101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Add_Req_102OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Add_Req_102)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    int getA();

    /**
     * <code>int32 b = 2;</code>
     * @return The b.
     */
    int getB();
  }
  /**
   * Protobuf type {@code Add_Req_102}
   */
  public static final class Add_Req_102 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Add_Req_102)
      Add_Req_102OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Add_Req_102.newBuilder() to construct.
    private Add_Req_102(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Add_Req_102() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Add_Req_102();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Add_Req_102(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              a_ = input.readInt32();
              break;
            }
            case 16: {

              b_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Req_102_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Req_102_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private int b_;
    /**
     * <code>int32 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (b_ != 0) {
        output.writeInt32(2, b_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 other = (com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102) obj;

      if (getA()
          != other.getA()) return false;
      if (getB()
          != other.getB()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Add_Req_102}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Add_Req_102)
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Req_102_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Req_102_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.Builder.class);
      }

      // Construct using com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Req_102_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 getDefaultInstanceForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 build() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 buildPartial() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 result = new com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102) {
          return mergeFrom((com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 other) {
        if (other == com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <code>int32 b = 2;</code>
       * @return The b.
       */
      @java.lang.Override
      public int getB() {
        return b_;
      }
      /**
       * <code>int32 b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Add_Req_102)
    }

    // @@protoc_insertion_point(class_scope:Add_Req_102)
    private static final com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102();
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Add_Req_102>
        PARSER = new com.google.protobuf.AbstractParser<Add_Req_102>() {
      @java.lang.Override
      public Add_Req_102 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Add_Req_102(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Add_Req_102> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Add_Req_102> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Req_102 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Add_Resp_102OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Add_Resp_102)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sum = 1;</code>
     * @return The sum.
     */
    int getSum();
  }
  /**
   * Protobuf type {@code Add_Resp_102}
   */
  public static final class Add_Resp_102 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Add_Resp_102)
      Add_Resp_102OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Add_Resp_102.newBuilder() to construct.
    private Add_Resp_102(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Add_Resp_102() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Add_Resp_102();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Add_Resp_102(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Resp_102_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Resp_102_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.Builder.class);
    }

    public static final int SUM_FIELD_NUMBER = 1;
    private int sum_;
    /**
     * <code>int32 sum = 1;</code>
     * @return The sum.
     */
    @java.lang.Override
    public int getSum() {
      return sum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sum_ != 0) {
        output.writeInt32(1, sum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 other = (com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102) obj;

      if (getSum()
          != other.getSum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUM_FIELD_NUMBER;
      hash = (53 * hash) + getSum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Add_Resp_102}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Add_Resp_102)
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Resp_102_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Resp_102_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.Builder.class);
      }

      // Construct using com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Add_Resp_102_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 getDefaultInstanceForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 build() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 buildPartial() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 result = new com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102(this);
        result.sum_ = sum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102) {
          return mergeFrom((com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 other) {
        if (other == com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102.getDefaultInstance()) return this;
        if (other.getSum() != 0) {
          setSum(other.getSum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sum_ ;
      /**
       * <code>int32 sum = 1;</code>
       * @return The sum.
       */
      @java.lang.Override
      public int getSum() {
        return sum_;
      }
      /**
       * <code>int32 sum = 1;</code>
       * @param value The sum to set.
       * @return This builder for chaining.
       */
      public Builder setSum(int value) {
        
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSum() {
        
        sum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Add_Resp_102)
    }

    // @@protoc_insertion_point(class_scope:Add_Resp_102)
    private static final com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102();
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Add_Resp_102>
        PARSER = new com.google.protobuf.AbstractParser<Add_Resp_102>() {
      @java.lang.Override
      public Add_Resp_102 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Add_Resp_102(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Add_Resp_102> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Add_Resp_102> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.test.protobuf.proto.TestProto.Add_Resp_102 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Notice_Push_103OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notice_Push_103)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 value = 1;</code>
     * @return The value.
     */
    long getValue();
  }
  /**
   * Protobuf type {@code Notice_Push_103}
   */
  public static final class Notice_Push_103 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Notice_Push_103)
      Notice_Push_103OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notice_Push_103.newBuilder() to construct.
    private Notice_Push_103(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notice_Push_103() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Notice_Push_103();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Notice_Push_103(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              value_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Notice_Push_103_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Notice_Push_103_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <code>int64 value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeInt64(1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103)) {
        return super.equals(obj);
      }
      com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 other = (com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103) obj;

      if (getValue()
          != other.getValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notice_Push_103}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notice_Push_103)
        com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Notice_Push_103_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Notice_Push_103_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.class, com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.Builder.class);
      }

      // Construct using com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.internal_static_Notice_Push_103_descriptor;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 getDefaultInstanceForType() {
        return com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.getDefaultInstance();
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 build() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 buildPartial() {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 result = new com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103) {
          return mergeFrom((com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 other) {
        if (other == com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <code>int64 value = 1;</code>
       * @return The value.
       */
      @java.lang.Override
      public long getValue() {
        return value_;
      }
      /**
       * <code>int64 value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(long value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Notice_Push_103)
    }

    // @@protoc_insertion_point(class_scope:Notice_Push_103)
    private static final com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103();
    }

    public static com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Notice_Push_103>
        PARSER = new com.google.protobuf.AbstractParser<Notice_Push_103>() {
      @java.lang.Override
      public Notice_Push_103 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notice_Push_103(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Notice_Push_103> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notice_Push_103> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.swingfrog.summer.test.protobuf.proto.TestProto.Notice_Push_103 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloWorld_Req_101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloWorld_Req_101_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloWorld_Resp_101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloWorld_Resp_101_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Add_Req_102_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Add_Req_102_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Add_Resp_102_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Add_Resp_102_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notice_Push_103_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Notice_Push_103_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"\024\n\022HelloWorld_Req_101\"\"\n\023He" +
      "lloWorld_Resp_101\022\013\n\003msg\030\001 \001(\t\"#\n\013Add_Re" +
      "q_102\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"\033\n\014Add_Resp_" +
      "102\022\013\n\003sum\030\001 \001(\005\" \n\017Notice_Push_103\022\r\n\005v" +
      "alue\030\001 \001(\003B5\n(com.swingfrog.summer.test." +
      "protobuf.protoB\tTestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloWorld_Req_101_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloWorld_Req_101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloWorld_Req_101_descriptor,
        new java.lang.String[] { });
    internal_static_HelloWorld_Resp_101_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloWorld_Resp_101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloWorld_Resp_101_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_Add_Req_102_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Add_Req_102_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Add_Req_102_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_Add_Resp_102_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Add_Resp_102_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Add_Resp_102_descriptor,
        new java.lang.String[] { "Sum", });
    internal_static_Notice_Push_103_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Notice_Push_103_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Notice_Push_103_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
